require("dotenv").config(); //OR require('dotenv/config')
const mongoose = require("mongoose");

// TO CREATE A DATABASE AND CONNECT TO IT
// 1. Login to MOngoDB Atlas and create a free CLUSTER or choose an existing free cluster.
// 2. Specify the connection URI to the MongoDB Atlas free cluster. The connection URI can be obtained
//    by clicking the "connect" button on the free cluster and then clicking "Driver" and then copy
//    the link. The link is then pasted in the ".env" file and edited to insert the password. To
//    edit the password, just clear the <db_password> and replace with your admin password which
//    is generated by going to: "Security -> Database Access"
//    Also go to: "Security -> Network Access" and add IP Address "0.0.0.0/0" to allow connection from
//    any IP address all over the world.
// 3. Specify the "name" of the database to be created in the free cluster in the ".env" file, then
//    write the "connection" code and the "schema-model" to  create the database and its collection
//    (i.e. similar to table in sql)
const dbconnect = async () => {
  try {
    const result = await mongoose.connect(process.env.DB_CONNECTION_URI, {
      dbName: process.env.DB_NAME,
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    if (result) console.log("MongoDB connection successful.");
    else console.log("MongoDB connection failed.");
  } catch (err) {
    console.error("Error connecting to MongoDB. ");
  }
};

module.exports = dbconnect;
